### ISSUE TITLE
Expected result as second argument instead of first

### ISSUE THREAD

**Issue by chrisharrison** [VladaHejda/PhpUnitAssertException#7]
Is there a reason why the expected result is the second argument of the `expectException` method?

In most of PHPUnit the convention seems to be that expected is the first argument.

**Comment by VladaHejda** [comment]
You're right, but...

- if I change API now, I'll break tests for those whose project depends on this repo, unless I change version to `2.0.0` (due to semver), and I think it's not desirable
- when I switch only first and second argument, it would look ugly when there's three expectation arguments not aligned subsequently
- otherwise when I switch all expectation parameters with `$test` callback, it's (at least for me) even uglier (imagine `assertException(null, null, Exception::class, $test)` - you don't want to write this every time you just test common Exception)
- all three expectations are optional, so my order of arguments is the easiest way for asserting

So, due to last 3 reasons I originally decided to use order as is. I don't think it would make problems to anyone writing tests, does it?

**Comment by chrisharrison** [comment]
Fair enough. And no, it does not cause any problems for writing tests. It was more of an aesthetics issue. But your reasonings are sound.
